teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.30  # No movement when turbo is not pressed
    # scale_linear_turbo:
    #   x: 1.0  # Full speed when turbo is pressed

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.76  # No rotation when turbo is not pressed
    # scale_angular_turbo:
    #   yaw: 1.0  # Full rotation speed when turbo is pressed

    enable_button: 4 # L2 shoulder button for normal mode
    # enable_turbo_button: 5 # Different button (e.g., L1 shoulder button) for turbo mode